version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    ports:
      - '4100:4100'
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
